namespace TradingPlatform.BusinessLayer;

/// <summary>
/// SettingItem cast type
/// </summary>
public enum SettingItemType
{
	Undefined,
	String,
	Boolean,
	BooleanSwitcher,
	Integer,
	Double,
	Selector,
	SelectorLocalized,
	DateTime,
	Account,
	Symbol,
	Password,
	Period,
	File,
	Group,
	RadioLocalized,
	Action,
	Font,
	TimeZone,
	Rss,
	HotkeyList,
	Object,
	ConditionSet,
	Alignment,
	PairColor,
	Color,
	Sound,
	LineOptions,
	TimeZoneManager,
	FibonacciLevelOptions,
	RangeSelector,
	DrawingPoints,
	TimeFrameConfig,
	BooleanLocalized,
	OAuth,
	Label,
	ClusterColoringLevels,
	ArbitageSymbols,
	TextArea,
	OrderRequestParameters,
	IconedAction,
	PnlAlertsContainer,
	TimeInTradeContainer,
	SymbolsList,
	Slider,
	DoubleWithLink,
	Custom,
	Long,
	MinotauroFibonacciLevelOptions,
	OTP,
	Condition,
	BigTextArea
}
